SCREEN_DIMENSIONS = (960, 600)
cursor_type = "normal"
cursor_held = False
number_of_stages = 7
stage_name_format = "stages/stage_$.txt"
output_file = "log_$.txt"
current_text = ""
starting_hovering_ball_t = 10.466
bouncing = False
